name: two_a
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+7

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.1
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  file_picker: ^5.5.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.14.0
  firebase_messaging: ^14.7.2
  firebase_storage: ^11.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_image_compress: ^2.1.0
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_timezone: ^1.0.7
  google_mobile_ads: ^4.0.0
  image_cropper: ^5.0.0
  intl: any
  open_file: ^3.3.2
  path: ^1.8.3
  path_provider: ^2.0.15
  provider: ^6.1.2
  restart_app: ^1.2.1
  showcaseview: ^2.1.1
  sqflite: ^2.3.0
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  generate: true
  assets:
     - images/logo/logo1.png
     - images/alarm/alarm.png
     - images/repeat/repeat.png
     - images/description/description.png
     - images/attach/attach.png
     - images/userIcon/userIcon.png
     - images/leftchevron/leftchevron.png
     - images/rightchevron/rightchevron.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-Light.ttf
    
